name: template

services:
    php:
        container_name: template-php
        image: ghcr.io/rbrauner/template/php:latest
        restart: unless-stopped
        working_dir: /var/www/html
        user: "${UID:-1000}:${GID:-1000}"
        environment:
            HOME: /home/${APP_USER:-app}
        tty: true
        networks:
            shared-network-internal:
            shared-network:
        volumes:
            - caddy-data:/data
            - caddy-config:/config
            - shared-home:/home/${APP_USER:-app}
            - .:/var/www/html
            - ./docker/php/prod/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/prod/Caddyfile:/etc/frankenphp/Caddyfile
        labels:
            traefik.enable: true
            traefik.http.services.template.loadbalancer.server.port: 80
            traefik.http.services.template-secure.loadbalancer.server.port: 443
            traefik.http.routers.template.rule: Host(`${DOMAIN:-template.com}`)
            traefik.http.routers.template.entrypoints: http
            traefik.http.routers.template.tls: false
            traefik.http.routers.template.service: template
            traefik.http.routers.template-secure.rule: Host(`${DOMAIN:-template.com}`)
            traefik.http.routers.template-secure.entrypoints: https
            traefik.http.routers.template-secure.tls: true
            traefik.http.routers.template-secure.service: template-secure
    node:
        container_name: template-node
        image: ghcr.io/rbrauner/template/node:latest
        restart: unless-stopped
        working_dir: /var/www/html
        user: "${UID:-1000}:${GID:-1000}"
        environment:
            HOME: /home/${APP_USER:-app}
        tty: true
        networks:
            shared-network-internal:
            shared-network:
        volumes:
            - shared-home:/home/${APP_USER:-app}
            - .:/var/www/html

networks:
    shared-network-internal:
        name: ${SHARED_NETWORK_NAME:-shared-network-internal}
        external: true
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
    caddy-data:
        name: template-caddy-data
    caddy-config:
        name: template-caddy-config
