services:
    caddy:
        container_name: template-caddy
        image: caddy:alpine
        restart: unless-stopped
        working_dir: /var/www/html
        # user: "${UID:-1000}:${GID:-1000}"
        # environment:
        #     HOME: /home/app
        networks:
            main:
        volumes:
            - caddy-data:/data
            - caddy-config:/config
            # - home:/home/app
            - .:/var/www/html
            - ./docker/caddy/dev/Caddyfile:/etc/caddy/Caddyfile
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.template.loadbalancer.server.port=80"
            - "traefik.http.services.template-secure.loadbalancer.server.port=443"
            - "traefik.http.routers.template.rule=Host(`${DOMAIN:-template.localhost}`)"
            - "traefik.http.routers.template.entrypoints=http"
            - "traefik.http.routers.template.tls=false"
            - "traefik.http.routers.template.service=template"
            - "traefik.http.routers.template-secure.rule=Host(`${DOMAIN:-template.localhost}`)"
            - "traefik.http.routers.template-secure.entrypoints=https"
            - "traefik.http.routers.template-secure.tls=true"
            - "traefik.http.routers.template-secure.service=template-secure"
            - "traefik.http.routers.wildcard-template.rule=HostRegexp(`.+\\.template\\.localhost`)"
            - "traefik.http.routers.wildcard-template.entrypoints=http"
            - "traefik.http.routers.wildcard-template.tls=false"
            - "traefik.http.routers.wildcard-template.service=template"
            - "traefik.http.routers.wildcard-template-secure.rule=HostRegexp(`.+\\.template\\.localhost`)"
            - "traefik.http.routers.wildcard-template-secure.entrypoints=https"
            - "traefik.http.routers.wildcard-template-secure.tls=true"
            - "traefik.http.routers.wildcard-template-secure.service=template-secure"

    php:
        container_name: template-php
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
            target: dev
            network: host
        restart: unless-stopped
        working_dir: /var/www/html
        user: "${UID:-1000}:${GID:-1000}"
        environment:
            HOME: /home/app
            # XDEBUG_SESSION: 1
        networks:
            main:
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - home:/home/app
            - .:/var/www/html

    change-volume-ownership:
        container_name: template-change-volume-ownership
        image: alpine
        command: chown -R ${UID:-1000}:${GID:-1000} /home/app
        restart: no
        user: root
        group_add:
            - ${GID:-1000}
        networks:
            - main
        volumes:
            - home:/home/app

networks:
    main:
        external: true

volumes:
    home:
        name: template-home
    caddy-data:
        name: template-caddy-data
    caddy-config:
        name: template-caddy-config
