services:
    caddy:
        container_name: template-caddy
        image: ghcr.io/rbrauner/template/caddy:latest
        restart: unless-stopped
        working_dir: /var/www/html
        # user: "${UID:-1000}:${GID:-1000}"
        networks:
            shared-network-internal:
        volumes:
            - caddy-data:/data
            - caddy-config:/config
            # - shared-home:/home/${APP_USER:-app}
            - .:/var/www/html
        labels:
            traefik.enable: "true"
            traefik.http.services.template.loadbalancer.server.port: "80"
            traefik.http.services.template-secure.loadbalancer.server.port: "443"
            traefik.http.routers.template.rule: "Host(`${DOMAIN:-template.com}`)"
            traefik.http.routers.template.entrypoints: "http"
            traefik.http.routers.template.tls: "false"
            traefik.http.routers.template.middlewares: "redirect-to-https@docker"
            traefik.http.routers.template.service: "template"
            traefik.http.routers.template-secure.rule: "Host(`${DOMAIN:-template.com}`)"
            traefik.http.routers.template-secure.entrypoints: "https"
            traefik.http.routers.template-secure.tls: "true"
            traefik.http.routers.template-secure.service: "template-secure"

    php:
        container_name: template-php
        image: ghcr.io/rbrauner/template/php:latest
        restart: unless-stopped
        working_dir: /var/www/html
        user: "${UID:-1000}:${GID:-1000}"
        networks:
            shared-network-internal:
            shared-network:
        volumes:
            - shared-home:/home/${APP_USER:-app}
            - .:/var/www/html

networks:
    shared-network-internal:
        name: ${SHARED_NETWORK_NAME:-shared-network-internal}
        external: true
    shared-network:
        name: ${SHARED_NETWORK_NAME:-shared-network}
        external: true

volumes:
    shared-home:
        name: ${SHARED_HOME_VOLUME:-shared-home}
        external: true
    caddy-data:
        name: template-caddy-data
    caddy-config:
        name: template-caddy-config
